### ISSUE TITLE
有向エッジと無向エッジの区別

### ISSUE THREAD

**Issue by ryotayamanaka** [g2gml/pg#3]
現在の PG 形式のエッジの表現では常に有効エッジを表現している。

現在の形式で無向エッジを表現しようとする場合、両方向に同じプロパティを持つエッジを作成する方法が考えられるが、この場合、エッジ ID がないためひとつの無向エッジなのかふたつの有効エッジなのかを判別することができない。

Neo4j、PGX、Gremlin の形式でも有効エッジのみが表現されている一方、Dot 形式のように矢印の有無で無向エッジを表現することが可能な形式もある。PG 形式は無向エッジを表現できるように拡張されるべきか？

**Comment by hchiba1** [comment]
例えばですが、先ほども話に出た一つのアイディアは、ノード行の2カラム目に -- や -> などを書くという案ですね.
(実際記述してみると、けっこう見やすい気も..)

**Comment by ryotayamanaka** [comment]
> ノード行の2カラム目に -- や -> などを書くという案
このシンタックスだとパース時の ノード or エッジ は2カラム目が単純に「-- or -> or <-」であるかどうかで判定できる。現在は 2カラム目がノード ID であるかどうか ＝「ダブルクォーテーションで囲われた一単語 or コロンを含まない一単語」という正規表現で判定している。

**Comment by ryotayamanaka** [comment]
Neo4j では無向エッジを格納する方法はないが、有向エッジの両方向をパターンマッチさせることができるので、片側だけの有効エッジを持たせておけばいいとのこと。検索時に、下の「friend_of」が（論理的に）無向エッジであるということを知っている必要がある。

> MATCH (a)-[:friend_of]-(b)

https://graphaware.com/neo4j/2013/10/11/neo4j-bidirectional-relationships.html

PGX や igraph ではグラフ単位で有向グラフか無向グラフかを指定することができ、有効エッジを無向エッジに変換することができる。アルゴリズムによって対象とするグラフが有向であるか無向であるか異なるため、その変換ができると便利、という背景を反映させている。

https://igraph.org/r/doc/as.directed.html

**Comment by ryotayamanaka** [comment]
無向エッジを追加することに決定。v0.3.0 で実装。

Added its description in the doc:
https://g2gml.readthedocs.io/en/latest/contents/pg-format.html#pg-flat-file

**Comment by ryotayamanaka** [comment]
各データベースに無向エッジ（特に Mixed Graph）をロードするときの変換方法については新しい issue を作成
