### ISSUE TITLE
Omitting node lines

### ISSUE THREAD

**Issue by ryotayamanaka** [g2gml/pg#30]
Is it ok to have one line as below?
```
a -> b :label prop:val
```

instead of:
```
a
b
a -> b :label prop:val
```

**Comment by ryotayamanaka** [comment]
Similar to the "blank node" in the RDF world?

```
a -> b :has

b -> b1
b -> b2
b -> b3
```

**Comment by ryotayamanaka** [comment]
Is this (explicitly) allowed/disallowed in the current PG syntax spec? @hchiba1

**Comment by hchiba1** [comment]
It is not treated at the PEG level.
We could explicitly allow/disallow at the application level.
It is a good idea to complement implicit nodes after parsing.

**Comment by hchiba1** [comment]
followed by the discussion:
https://github.com/orgs/pg-format/discussions/16
