### ISSUE TITLE
Update incomplete specification of PG format

### ISSUE THREAD

**Issue by nichtich** [g2gml/pg#33]
The [current specification of PG serialization](https://pg-format.readthedocs.io/en/0.4/contents/reference.html#serialization) does not match the implementation:

- comments are not mentioned
- multiline-nodes are not allowed
- NODE_ID is not defined
- String and its value escaping is not defined
- Number is not defined

**Comment by nichtich** [comment]
First complete draft at https://github.com/gbv/pg/blob/main/docs/pg-format.md for feedback. See https://github.com/gbv/pgraph/blob/main/docs/pg-format.pg for a PG file describing the format with examples.

I tried to cover all edge cases by unit test of PG parser and serializer.

**Comment by hchiba1** [comment]
Left a note here:
https://github.com/pg-format/pg-formatter/wiki

**Comment by nichtich** [comment]
Created repository https://github.com/pg-format/specification#readme for formal writing (only PG-JSON(L) so far).
