### ISSUE TITLE
Align data types with JSON/PSQL/Cypher

### ISSUE THREAD

**Issue by nichtich** [g2gml/pg#34]
As far as I managed to dig into OpenCypher and SQL/PSQL, their property graph model allows property values to be string, number (without explicit limtation to double floating point, but in practice I bet its the same), boolean, and null. This is equal to atomic data types JSON and should be supported by PG as well.

Adding boolean and null to PG/JSON is no big deal but in textual serialization this might break backwards compatibility as `a:true b:null` is currently read as `a:"true" b:"null"`.

**Comment by nichtich** [comment]
This has been finished in pgraph and discussed at https://github.com/g2glab/pg-formatter/discussions/14, so this issue can be closed.

**Comment by hchiba1** [comment]
By the way, as a side note, what did you mean by PSQL? (Just checking to make sure.)

**Comment by nichtich** [comment]
Sorry for typo: so many acronyms! I meant [PGQL](https://pgql-lang.org/)
