### ISSUE TITLE
Rewrite and publish at npm

### ISSUE THREAD

**Issue by nichtich** [g2gml/pg#35]
I've started to rewrite the code at the for at https://github.com/gbv/pg with more modern JavaScript, modularization and unit tests. I would be happy to join and help to publish a package at npm (suggested name: `pgraph` but another name is good as well).

**Comment by ryotayamanaka** [comment]
Sounds cool 👍 

For the name, we tried some google searches and found most short names get conflicts. So we could suggest `pg-generic` or `pg-standard`, but we would rather respect your preference. `pgraph` sounds good as well.

**Comment by nichtich** [comment]
Current state of rewrite:

- [x] PG format and JSON parser / serializer
- [x] DOT parser / serializer
- [x] Amazon Neptune serializer
- [ ] Amazon Neptune parser 
- [ ] Oracle PGX serializer
- [ ] Oracle PGX parser
- [ ] Docker file

**Comment by nichtich** [comment]
I lost myself in research on property graph serializations and [implemented some more formats](https://github.com/gbv/pgraph?tab=readme-ov-file#cli) but I don't use Oracle PGX nor Neptune so this will have to wait. The rewrite also resulted in some changes of the PG data model (#34) and [PG syntax](https://github.com/gbv/pgraph/blob/main/docs/pg-format.md). For the latter I think about further adding better syntax for multivalues to allow `1 :person name:Alice,Carol` as shortcut for `1 :person name:Alice name:Carol` both parsed into `{"id":"1","labels":["person"],"properties":{"name":["Alice","Carol"]}}` but that's it - more features would only make the format too complicated.

The current PG parser [is hand-written](https://github.com/gbv/pgraph/blob/main/src/parser/pg.js) instead of a grammer. If you extend [your grammer](https://github.com/g2glab/pg-formatter/blob/main/lib/pg.pegjs) to be aligned with the extensions, I could switch to pegjs. See [examples directory](https://github.com/gbv/pgraph/tree/main/examples) for `.pg` files and corresponding parsed graph as `.json` as test cases.

**Comment by hchiba1** [comment]
I am trying to update the code in [pg-formatter](https://github.com/g2glab/pg-formatter), too.
Maybe refactoring and tests are needed.

**Comment by ryotayamanaka** [comment]
> allow `1 :person name:Alice,Carol as shortcut`

Very interesting. But, yes, I agree that the balance between readability and syntax complexity is important.

**Comment by nichtich** [comment]
From my point of view the current state of pgraph is ready to be published but I better wait to decide on open questions:

- allowed characters at start of and in names (see https://github.com/g2glab/pg-formatter/discussions/11)
- when/whether to require space between key and value of a property (currently its not, what do you think?)
- allow list syntax for repeated properties (as illustrated above, already implemented, what do you think?)
- data types (currently JSON types only but some property graph database management systems have additional types)
- where to host the pgraph repository (could also be moved later if wanted)

**Comment by nichtich** [comment]
I'd like to publish a release of pgraph at npm to facilitate colleauges to work with it. The repository could also be moved to g2glab organization or another organization as you prefer. The documentation states that details of PG format are still being discussed.

**Comment by hchiba1** [comment]
I have no objection, provided there is room for specification changes.

Discussions so far:
* https://github.com/g2glab/pg-formatter/discussions/11
* https://github.com/g2glab/pg-formatter/discussions/13
* https://github.com/g2glab/pg-formatter/discussions/15
* https://github.com/g2glab/pg-formatter/discussions/14

Let us continue the discussions. @ryotayamanaka @shota-matsumoto-lm

**Comment by nichtich** [comment]
I had to rename it to `pgraphs` because of npm, so here it is: https://www.npmjs.com/package/pgraphs

**Comment by hchiba1** [comment]
Other package named `pgraph`?

**Comment by nichtich** [comment]
There is a package `p-graph` so `pgraph` is forbidden to avoid accidental confusion.
