### ISSUE TITLE
JSON-PG について考える

### ISSUE THREAD

**Issue by ryotayamanaka** [g2gml/pg#8]
テキスト・ファイルとしての PG 形式は読みやすさ・書きやすさを重視しているが、これをクライアント・アプリケーションで描画する場合などには JSON になっていると便利。PG 形式の持つ表現力と制約をそのままに、JSON にした JSON-PG 形式を定義して、PG と JSON-PG を相互に変換できるようにすることを検討したい。

**Comment by ryotas** [comment]
Node ID, Fron Node ID, To Node ID, Label に対する予約語が必要になる。

**Comment by ryotayamanaka** [comment]
Added its short description here.
https://g2gml.readthedocs.io/en/latest/contents/pg-format.html#json-pg

**Comment by ryotayamanaka** [comment]
プロパティ値として配列を扱えるようにするかどうかについては PG Flat でも考える必要があるので別途 issue を作成する。

**Comment by ryotayamanaka** [comment]
プロパティ値として配列を扱えるようにするかどうかについては PG Flat でも考える必要があるので別途 issue を作成する。
